### ISSUE TITLE
Unable to create index - ERROR: syntax error at or near "."

### ISSUE THREAD

**Issue by wreiske** [fcoury/oxide#60]
Hello! I'm working on testing Oxide and FerretDB with Meteor. 
https://github.com/meteor/meteor/discussions/12150

While testing Oxide, I ran into an issue with creating an index.

https://github.com/meteor/meteor/discussions/12150#discussioncomment-3469279

```
postgres    | 2022-08-24 20:42:36.260 UTC [1] LOG:  database system is ready to accept connections
setup       | CREATE SCHEMA
setup exited with code 0
oxide       | [2022-08-24T20:42:45Z INFO  oxide::server] OxideDB listening on 0.0.0.0:27017...
meteor_app  | Successfully connected to MongoDB
meteor_app  | Starting app...
postgres    | 2022-08-24 20:42:46.281 UTC [80] ERROR:  syntax error at or near "." at character 41
postgres    | 2022-08-24 20:42:46.281 UTC [80] STATEMENT:  CREATE UNIQUE INDEX IF NOT EXISTS emails.address_1 ON "meteor"."users" ((_jsonb->'emails.address'))
oxide       | thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: db error: ERROR: syntax error at or near "."
oxide       | 
oxide       | Caused by:
oxide       |     ERROR: syntax error at or near "."
oxide       | 
oxide       | Location:
oxide       |     /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/convert/mod.rs:550:9', src/commands/create_indexes.rs:33:18
oxide       | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
meteor_app  | 
meteor_app  | /opt/bundle/bundle/programs/server/node_modules/fibers/future.js:313
meteor_app  |                                           throw(ex);
meteor_app  |                                           ^
meteor_app  | errorClass [Error]: [An error occurred when creating an index for collection "users: connection 1 to 172.20.0.6:27017 closed]
meteor_app  |     at Collection.createIndex (packages/mongo/collection.js:770:15)
meteor_app  |     at setupUsersCollection (packages/accounts-base/accounts_server.js:1813:9)
meteor_app  |     at new AccountsServer (packages/accounts-base/accounts_server.js:74:5)
meteor_app  |     at packages/accounts-base/server_main.js:7:12
meteor_app  |     at module (packages/accounts-base/server_main.js:19:1)
meteor_app  |     at fileEvaluate (packages/modules-runtime.js:336:7)
meteor_app  |     at Module.require (packages/modules-runtime.js:238:14)
meteor_app  |     at require (packages/modules-runtime.js:258:21)
meteor_app  |     at /opt/bundle/bundle/programs/server/packages/accounts-base.js:2395:15
meteor_app  |     at /opt/bundle/bundle/programs/server/packages/accounts-base.js:2402:3
meteor_app  |     at /opt/bundle/bundle/programs/server/boot.js:401:38
meteor_app  |     at Array.forEach (<anonymous>)
meteor_app  |     at /opt/bundle/bundle/programs/server/boot.js:226:21
meteor_app  |     at /opt/bundle/bundle/programs/server/boot.js:464:7
meteor_app  |     at Function.run (/opt/bundle/bundle/programs/server/profile.js:280:14)
meteor_app  |     at /opt/bundle/bundle/programs/server/boot.js:463:13 {
meteor_app  |   isClientSafe: true,
meteor_app  |   error: 'An error occurred when creating an index for collection "users: connection 1 to 172.20.0.6:27017 closed',
meteor_app  |   reason: undefined,
meteor_app  |   details: undefined,
meteor_app  |   errorType: 'Meteor.Error'
meteor_app  | }
meteor_app exited with code 1
```

This may be related to the code here: https://github.com/fcoury/oxide/commit/192f076f6e65d1d41b4f6ce53a53db121051b3fe

An example object for testing would be:

```
{
  "_id": "5QGdzKp2nCKtwz9QJ",
  "emails": [
    {
      "address": "wreiske@mieweb.com",
      "verified": true
    }
  ],
  "profile": {
    "username": "wreiske",
    "name": "Will Reiske",
    "photo": "https://s.gravatar.com/avatar/f830b06583b46bd48115f506b98d5689?s=512&d=mp",
  }
}
```

Creating an index on `emails.address` fails.

**Comment by fcoury** [comment]
Thank you so much for your testing and for reporting this. It may take me a few days to be able to replicate it and write an automated test, but I will reply here as soon as I can get to it!

**Comment by fcoury** [comment]
Actually the problem is that we're not allowing indexes on nested fields, but should be trivial to add. Work is very demanding right now but I think I know how to fix it.

**Comment by fcoury** [comment]
As you can see I couldn't resist and fixed the issue. Is there a way you can test again from source?

**Comment by fcoury** [comment]
@wreiske as you can see I couldn't wait and fixed the issue. Is there a way you can test again from source? Let me know.

**Comment by wreiske** [comment]
> @wreiske as you can see I couldn't wait and fixed the issue. Is there a way you can test again from source? Let me know.

@fcoury , that worked! But now I'm having another issue, https://github.com/fcoury/oxide/issues/62

I've published my test docker-compose to reproduce the issues here: https://github.com/wreiske/meteor-oxide

Thank you! 🙏
