### ISSUE TITLE
Got unknown OP_MSG command: count

### ISSUE THREAD

**Issue by wreiske** [fcoury/oxide#62]
Hello! I'm working on testing OxideDB and FerretDB with Meteor. 
https://github.com/meteor/meteor/discussions/12150

Thank you for your incredibly fast PR and fix for https://github.com/fcoury/oxide/issues/60. I've pulled in the latest changes and now I'm having this issue:

```
oxide       | [2022-08-25T21:13:17Z INFO  oxide::server] OxideDB listening on 0.0.0.0:27017...
meteor_app  | Successfully connected to MongoDB
meteor_app  | Starting app...
oxide       | [2022-08-25T21:13:18Z ERROR oxide::handler] Got unknown OP_MSG command: count
oxide       |     [Document({"count": String("tasks"), "query": Document({}), "$db": String("meteor")})]
meteor_app  | /opt/bundle/bundle/programs/server/node_modules/fibers/future.js:313
meteor_app  |                                           throw(ex);
meteor_app  |                                           ^
meteor_app  | 
meteor_app  | MongoServerError: no such command: 'count'
meteor_app  |     at MessageStream.messageHandler (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:462:30)
meteor_app  |     at MessageStream.emit (events.js:400:28)
meteor_app  |     at MessageStream.emit (domain.js:475:12)
meteor_app  |     at processIncomingData (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
meteor_app  |     at MessageStream._write (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
meteor_app  |     at writeOrBuffer (internal/streams/writable.js:358:12)
meteor_app  |     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
meteor_app  |     at Socket.ondata (internal/streams/readable.js:731:22)
meteor_app  |     at Socket.emit (events.js:400:28)
meteor_app  |     at Socket.emit (domain.js:475:12)
meteor_app  |     at addChunk (internal/streams/readable.js:293:12)
meteor_app  |     at readableAddChunk (internal/streams/readable.js:267:9)
meteor_app  |     at Socket.Readable.push (internal/streams/readable.js:206:10)
meteor_app  |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
meteor_app  |   ok: 0,
meteor_app  |   code: 59,
meteor_app  |   codeName: 'CommandNotFound'
meteor_app  | }
meteor_app exited with code 1
```

Thank you for all that you do!

**Comment by fcoury** [comment]
OK for this case, we're not yet supporting the `count` command. However it's basically already implemented as part of the aggregation pipeline. I'll evaluate how quick I can implement this one.

Let's see how far we can push! 😊
